### ISSUE TITLE
Users can't destory locks because invalid character in player name

### ISSUE THREAD

**Issue by Yang-qwq** [NyaaCat/LockettePro#18]
This is a name that can be a bug `Butter#7550`
When he using the plugin, a lock with below texts will created.
```plain
[私有]
Butter#7550#(uuid)
```
And after that, he can't doing anything because the uuid doesn't match
*(All the above is my infer, if i saying sth wrong, please understand me)*

**Comment by joshi1999** [comment]
Hello,

I have some question about that:

- On which Server Software is your server running? [Spigot/Paper/....]
- Is your server in offline-mode? [For example, cracked player can play on that server]

Best regards
joshi1999

**Comment by Yang-qwq** [comment]
I'm using Paper build 388 (1.18.2) for my server, and it's running in offline mode.

**Comment by joshi1999** [comment]
Ah,  yes it's an invalid character in the name. The plugin checks for '#' and uses the part after '#' as uuid. You could change that and deploy it on your server. Also you could do a pullrequest, but I don't think it will be accepted because it is adressing a problem on invalid names, which aren't normaly possible ^^

**Comment by Yang-qwq** [comment]
thanks
